version: 0.1
phases:
  pre_build:
    commands:
     - echo Installing NPM dependencies
     - npm install
     - npm install aws-amplify @aws-amplify/ui-vue
     - npm install -g @aws-amplify/cli
  build:
    commands:
     - echo Build start on `date`
     - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
